### ISSUE TITLE
数据集预处理存在问题

### ISSUE THREAD

**Issue by wssybsch** [YorkQiu/PeopleRelationNetwork#1]
您好，我通过运行数据预处理得程序发现，MS数据集在进行预处理会报两个错，分别是边界框超出范围和标签可能存在两个或者两个以上1得情况，也就是重要人物不唯一。想请问您有没有处理好得数据集可以提供学习，麻烦您了。

**Comment by YorkQiu** [comment]
您好，数据预处理的其中一个目的也包括数据的清洗。我们对这两种情况分别是这么处理的：
1. 对于bounding box超出范围的人物，我们会直接将其去除。（请见preprocess_datasets.py的calib_boxes函数）。
2. 对于存在两个以上重要人物，我们以及参与讨论的审稿人都认为这是一种潜在的合理情况（即在收集数据的时候，标数据的人认为这两个人同样重要）。当然，您也可以认为这是一种不合理的情况，希望将其清洗掉。a) 如果您希望像我们一样保留有多个人的数据，在数据预处理的时候加上--need_multi_vip即可。b) 如果您希望去掉这些数据，不带这个参数即可。本文的实验都是在保留同一张图片可能出现多个重要人物的条件下进行的。

关于这两点的具体实现，您可以参考我们的preprocess_datasets.py文件。

**Comment by wssybsch** [comment]
感谢您的解答。非常感谢





------------------ 原始邮件 ------------------
发件人: YorkQiu ***@***.***&gt;
发送时间: 2023年10月11日 09:55
收件人: YorkQiu/PeopleRelationNetwork ***@***.***&gt;
抄送: wssybsch ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [YorkQiu/PeopleRelationNetwork] 数据集预处理存在问题 (Issue #1)





 
您好，数据预处理的其中一个目的也包括数据的清洗。我们对这两种情况分别是这么处理的：
  
对于bounding box超出范围的人物，我们会直接将其去除。（请见preprocess_datasets.py的calib_boxes函数）。
 
对于存在两个以上重要人物，我们以及参与讨论的审稿人都认为这是一种潜在的合理情况（即在收集数据的时候，标数据的人认为这两个人同样重要）。当然，您也可以认为这是一种不合理的情况，希望将其清洗掉。a) 如果您希望像我们一样保留有多个人的数据，在数据预处理的时候加上--need_multi_vip即可。b) 如果您希望去掉这些数据，不带这个参数即可。本文的实验都是在保留同一张图片可能出现多个重要人物的条件下进行的。
  
关于这两点的具体实现，您可以参考我们的preprocess_datasets.py文件。
